// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type FacebookAd struct {
	ID                        int64          `json:"id"`
	AdID                      sql.NullInt64  `json:"ad_id"`
	PageID                    sql.NullInt64  `json:"page_id"`
	PageName                  sql.NullString `json:"page_name"`
	AdSnapshotUrl             sql.NullString `json:"ad_snapshot_url"`
	AdCreativeBody            sql.NullString `json:"ad_creative_body"`
	AdCreativeLinkCaption     sql.NullString `json:"ad_creative_link_caption"`
	AdCreativeLinkDescription sql.NullString `json:"ad_creative_link_description"`
	AdCreativeLinkTitle       sql.NullString `json:"ad_creative_link_title"`
	AdDeliveryStartTime       sql.NullString `json:"ad_delivery_start_time"`
	AdDeliveryStopTime        sql.NullString `json:"ad_delivery_stop_time"`
	FundingEntity             sql.NullString `json:"funding_entity"`
	ImpressionsMin            sql.NullString `json:"impressions_min"`
	SpendMin                  sql.NullInt64  `json:"spend_min"`
	SpendMax                  sql.NullInt64  `json:"spend_max"`
	Currency                  sql.NullString `json:"currency"`
	AdUrl                     sql.NullString `json:"ad_url"`
	SocialMediaFacebook       sql.NullString `json:"social_media_facebook"`
	SocialMediaInstagram      sql.NullString `json:"social_media_instagram"`
	SocialMediaWhatsapp       sql.NullString `json:"social_media_whatsapp"`
	SearchTerms               sql.NullString `json:"search_terms"`
	CreatedAt                 interface{}    `json:"created_at"`
}

type FacebookDemo struct {
	ID                  int64          `json:"id"`
	AdID                sql.NullInt64  `json:"ad_id"`
	PageID              sql.NullInt64  `json:"page_id"`
	Age                 sql.NullInt32  `json:"age"`
	Gender              sql.NullString `json:"gender"`
	Percentage          interface{}    `json:"percentage"`
	AdDeliveryStartTime sql.NullString `json:"ad_delivery_start_time"`
	CreatedAt           interface{}    `json:"created_at"`
}

type FacebookRegion struct {
	ID                  int64          `json:"id"`
	AdID                sql.NullInt64  `json:"ad_id"`
	PageID              sql.NullInt64  `json:"page_id"`
	Region              sql.NullInt32  `json:"region"`
	Percentage          sql.NullString `json:"percentage"`
	AdDeliveryStartTime sql.NullString `json:"ad_delivery_start_time"`
	CreatedAt           interface{}    `json:"created_at"`
}
