// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
	"time"
)

type FacebookAd struct {
	AdID                      int64          `json:"ad_id"`
	JobID                     sql.NullInt64  `json:"job_id"`
	PageID                    sql.NullInt64  `json:"page_id"`
	PageName                  sql.NullString `json:"page_name"`
	AdSnapshotUrl             sql.NullString `json:"ad_snapshot_url"`
	AdCreativeBody            sql.NullString `json:"ad_creative_body"`
	AdCreativeLinkCaption     sql.NullString `json:"ad_creative_link_caption"`
	AdCreativeLinkDescription sql.NullString `json:"ad_creative_link_description"`
	AdCreativeLinkTitle       sql.NullString `json:"ad_creative_link_title"`
	AdDeliveryStartTime       sql.NullString `json:"ad_delivery_start_time"`
	AdDeliveryStopTime        sql.NullString `json:"ad_delivery_stop_time"`
	FundingEntity             sql.NullString `json:"funding_entity"`
	ImpressionsMin            sql.NullInt32  `json:"impressions_min"`
	ImpressionsMax            sql.NullInt32  `json:"impressions_max"`
	SpendMin                  sql.NullInt32  `json:"spend_min"`
	SpendMax                  sql.NullInt32  `json:"spend_max"`
	Currency                  sql.NullString `json:"currency"`
	AdUrl                     sql.NullString `json:"ad_url"`
	SocialMediaFacebook       sql.NullString `json:"social_media_facebook"`
	SocialMediaInstagram      sql.NullString `json:"social_media_instagram"`
	SocialMediaWhatsapp       sql.NullString `json:"social_media_whatsapp"`
	SearchTerms               sql.NullString `json:"search_terms"`
	AdCreationTime            sql.NullString `json:"ad_creation_time"`
	PotentialReachMax         sql.NullInt32  `json:"potential_reach_max"`
	PotentialReachMin         sql.NullInt32  `json:"potential_reach_min"`
	CreatedAt                 time.Time      `json:"created_at"`
}

type FacebookDemo struct {
	ID                  int64          `json:"id"`
	JobID               sql.NullInt64  `json:"job_id"`
	AdID                sql.NullInt64  `json:"ad_id"`
	PageID              sql.NullInt64  `json:"page_id"`
	Age                 sql.NullString `json:"age"`
	Gender              sql.NullString `json:"gender"`
	Percentage          sql.NullString `json:"percentage"`
	AdDeliveryStartTime sql.NullString `json:"ad_delivery_start_time"`
	CreatedAt           time.Time      `json:"created_at"`
}

type FacebookJob struct {
	ID                 int64          `json:"id"`
	SearchTerms        sql.NullString `json:"search_terms"`
	AccessToken        sql.NullString `json:"access_token"`
	PageTotal          sql.NullInt64  `json:"page_total"`
	SearchTotal        sql.NullInt64  `json:"search_total"`
	AdActiveStatus     sql.NullString `json:"ad_active_status"`
	AdDeliveryDateMax  sql.NullString `json:"ad_delivery_date_max"`
	AdDeliveryDateMin  sql.NullString `json:"ad_delivery_date_min"`
	AdReachedCountries sql.NullString `json:"ad_reached_countries"`
	TotalFoundAds      sql.NullInt64  `json:"total_found_ads"`
	CreatedAt          time.Time      `json:"created_at"`
}

type FacebookRegion struct {
	ID                  int64          `json:"id"`
	JobID               sql.NullInt64  `json:"job_id"`
	AdID                sql.NullInt64  `json:"ad_id"`
	PageID              sql.NullInt64  `json:"page_id"`
	Region              sql.NullString `json:"region"`
	Percentage          sql.NullString `json:"percentage"`
	AdDeliveryStartTime sql.NullString `json:"ad_delivery_start_time"`
	CreatedAt           time.Time      `json:"created_at"`
}
