// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	CreateFacebookAd(ctx context.Context, arg CreateFacebookAdParams) (FacebookAd, error)
	CreateFacebookDemo(ctx context.Context, arg CreateFacebookDemoParams) (FacebookDemo, error)
	CreateFacebookRegion(ctx context.Context, arg CreateFacebookRegionParams) (FacebookRegion, error)
	DeleteFaceookAd(ctx context.Context, id int64) error
	DeleteFaceookDemo(ctx context.Context, id int64) error
	DeleteFaceookRegion(ctx context.Context, id int64) error
	GetFacebookAd(ctx context.Context, id int64) (FacebookAd, error)
	GetFacebookDemo(ctx context.Context, id int64) (FacebookDemo, error)
	GetFacebookRegion(ctx context.Context, id int64) (FacebookRegion, error)
	ListFacebookAds(ctx context.Context, arg ListFacebookAdsParams) ([]FacebookAd, error)
	ListFacebookAdsByAdID(ctx context.Context, arg ListFacebookAdsByAdIDParams) ([]FacebookAd, error)
	ListFacebookAdsByPageID(ctx context.Context, arg ListFacebookAdsByPageIDParams) ([]FacebookAd, error)
	ListFacebookAdsByPageName(ctx context.Context, arg ListFacebookAdsByPageNameParams) ([]FacebookAd, error)
	ListFacebookDemos(ctx context.Context, arg ListFacebookDemosParams) ([]FacebookDemo, error)
	ListFacebookDemosByAdID(ctx context.Context, arg ListFacebookDemosByAdIDParams) ([]FacebookDemo, error)
	ListFacebookDemosByPageID(ctx context.Context, arg ListFacebookDemosByPageIDParams) ([]FacebookDemo, error)
	ListFacebookRegions(ctx context.Context, arg ListFacebookRegionsParams) ([]FacebookRegion, error)
	ListFacebookRegionsByAdID(ctx context.Context, arg ListFacebookRegionsByAdIDParams) ([]FacebookRegion, error)
	ListFacebookRegionsByPageID(ctx context.Context, arg ListFacebookRegionsByPageIDParams) ([]FacebookRegion, error)
}

var _ Querier = (*Queries)(nil)
